server:
  port: 8080
  host: "127.0.0.1"
  external_url: "https://live.yourdomain.com"  # Public URL for Nostr events

rtmp:
  port: 1935
  host: "localhost"  # Set this to your server's IP address
  # Connect from OBS using: rtmp://localhost:1935/live (no stream key needed)

# Path to the stream info YAML file (optional, defaults to "stream-info.yml")
# You can put this file anywhere you want
stream_info_path: "stream-info.yml"

nostr:
  private_key: "your-nostr-private-key-nsec"  # Your nsec private key (e.g., nsec1abc...)
  delete_non_recorded: false  # Send NIP-09 deletion requests for streams without recordings
  relays:
    - "wss://relay.damus.io"
    - "wss://nos.lol"
    - "wss://relay.nostr.band"