# configs/config.example.yml
server:
  port: 8080
  host: "0.0.0.0"

stream:
  rtmp_url: "rtmp://127.0.0.1:1935/live/stream"
  output_dir: "web/live"
  archive_dir: "web/live/past-streams"
  check_interval: 5s

hls:
  segment_time: 10
  playlist_size: 10

nostr:
  config_file: "configs/nostr.yml"

metadata:
  config_file: "configs/stream.yml"
