title: "My Live Stream"
summary: "Welcome to my live stream! We'll be coding, chatting, and having fun."
image: "https://example.com/stream-thumbnail.jpg"
tags:
  - "live"
  - "coding"
  - "tech"
  - "tutorial"
